### ISSUE TITLE
onboard unified ci

### ISSUE THREAD

**Issue by petar** [ipld/edelweiss#15]

**Comment by petar** [comment]
@biglep Is there a unified CI specialist who can onboard this repo? Thanks!

**Comment by BigLep** [comment]
@petar : please ask in IPFS Discord / #ip-productivity.
Lets first ask if there is a guide for how to onboard a new repo.
Ideally the team should be making it self-service for others to do rather than doing it themselves.

**Comment by petar** [comment]
Resolved by https://github.com/protocol/.github/pull/304
