### ISSUE TITLE
synchronize context cancellation with writing to the result channel

### ISSUE THREAD

**Issue by petar** [ipld/edelweiss#34]
Generated client method implementations must stop writing to the result channels as soon as they see "context cancelled".
This relieves clients from the responsibility to drain the result channel after they cancel the context.

A few changes in the generated code are required:

When context cancellation is detected, an error message should not be sent to the result channel:
https://github.com/ipld/edelweiss/blob/main/blueprints/services/dagjson-over-http/client.go#L284

All writing to the result channel should be paired with synchronized checks for context cancellation:
https://github.com/ipld/edelweiss/blob/main/blueprints/services/dagjson-over-http/client.go#L293
https://github.com/ipld/edelweiss/blob/main/blueprints/services/dagjson-over-http/client.go#L299
https://github.com/ipld/edelweiss/blob/main/blueprints/services/dagjson-over-http/client.go#L304
https://github.com/ipld/edelweiss/blob/main/blueprints/services/dagjson-over-http/client.go#L310

**Comment by BigLep** [comment]
Also, it looks like we'll need to associate this repo with w3dt-stewards team as well.  That can be in the same PR.

**Comment by ajnavarro** [comment]
@BigLep done here: https://github.com/ipld/github-mgmt/pull/9

**Comment by guseggert** [comment]
What if Edelweiss returns iterators for these collections, and only generates a sync method instead of sync+async? It's pretty surprising that the sync method also spawns a goroutine, and it'd remove all this confusing async machinery, and if consumer wants async, they can just wrap it in a goroutine, which is a lot easier IMO since they'd own the entire lifetime of the channel and goroutine, cancellation semantics, etc.

**Comment by ajnavarro** [comment]
@guseggert I created an issue with a proposal for using iterators instead of channels here: https://github.com/ipld/edelweiss/issues/38

**Comment by ajnavarro** [comment]
Hey @petar I created a draft PR to see if it is what we are looking for, can you have a look? https://github.com/ipld/edelweiss/pull/40 
Thanks.
