### ISSUE TITLE
Robustify the roadmap (202202 edition)

### ISSUE THREAD

**Issue by BigLep** [ipld/edelweiss#4]
Concerning https://github.com/ipld/edelweiss/blob/main/design/roadmap.md

Things coming to mind:
1. Dates: what are we targeting for all of these items?
2. Maybe add an item for generating the MVP user experience:
 - User defines a schema looking like X
 - They type Y
 - They get generated RPC client and server code that looks like Z
2. Maybe add something like "stakeholder commitment on type system design"
3. For the 3 items you have listed, maybe break into a date for the various stages: PR, merge, followup tests 
4. Discuss testing stages

**Comment by BigLep** [comment]
Also, a project board may be of use for tracking the current state of what's in progress, what's next, etc.

**Comment by petar** [comment]
User-facing MVP deliverable in main README.md. Roadmap updated. I think a project board will make sense after the MVP issue https://github.com/ipld/edelweiss/issues/3 is closed.
